cmake_minimum_required(VERSION 3.20)

project(test_riscv_hwprobe C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

add_executable(test_riscv_hwprobe src/main.c)
target_compile_options(test_riscv_hwprobe PRIVATE -Wall -Wextra -Werror)

install(TARGETS test_riscv_hwprobe RUNTIME DESTINATION usr/bin)
